// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP4Q029lrHuDPAmrXcbZEM0gUpmufdL0A',
    appId: '1:594395687064:web:6879030fc7eb8fea1388ed',
    messagingSenderId: '594395687064',
    projectId: 'velora-e-commerce-81f5f',
    authDomain: 'velora-e-commerce-81f5f.firebaseapp.com',
    storageBucket: 'velora-e-commerce-81f5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dKwhZBT5U9wflCvfeYrwu5v4kuWmDPk',
    appId: '1:594395687064:android:03dbed732cc084d81388ed',
    messagingSenderId: '594395687064',
    projectId: 'velora-e-commerce-81f5f',
    storageBucket: 'velora-e-commerce-81f5f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5cU3-B8mVcyHl4XzNdZglYXWGiHcEP8',
    appId: '1:594395687064:ios:8434ae06bec9dd0c1388ed',
    messagingSenderId: '594395687064',
    projectId: 'velora-e-commerce-81f5f',
    storageBucket: 'velora-e-commerce-81f5f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj5cU3-B8mVcyHl4XzNdZglYXWGiHcEP8',
    appId: '1:594395687064:ios:8434ae06bec9dd0c1388ed',
    messagingSenderId: '594395687064',
    projectId: 'velora-e-commerce-81f5f',
    storageBucket: 'velora-e-commerce-81f5f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP4Q029lrHuDPAmrXcbZEM0gUpmufdL0A',
    appId: '1:594395687064:web:ccf2c0f35789190d1388ed',
    messagingSenderId: '594395687064',
    projectId: 'velora-e-commerce-81f5f',
    authDomain: 'velora-e-commerce-81f5f.firebaseapp.com',
    storageBucket: 'velora-e-commerce-81f5f.firebasestorage.app',
  );
}
